apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: client
build:
  artifacts:
  - image: orim/client
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/*.yml
profiles:
- name: kind
  patches:
  - op: replace
    path: /build/artifacts/0/image
    value: localhost:5001/client