apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: site
  name: site
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: site
  strategy: {}
  template:
    metadata:
      labels:
        app: site
    spec:
      containers:
      - image: gcr.io/theta-computing-366519/client:latest
        name: site
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "256Mi"
            cpu: "1"
          limits:
            memory: "256Mi"
            cpu: "1"
