# Overrides values from: https://github.com/googleforgames/agones/blob/release-1.26.0/install/helm/agones/values.yaml
agones:
  # Almost identical to default; Example=true&PlayerTracking=false
  featureGates: CustomFasSyncInterval=true&PlayerAllocationFilter=false&PlayerTracking=true&ResetMetricsOnDelete=false&SDKGracefulTermination=false&StateAllocationFilter=true
  allocator:
    replicas: 2
    disableMTLS: true # do not do this in production! this is here to simplify the example
    disableTLS: true # do not do this in production! this is here to simplify the example
    service:
      name: agones-allocator
      # by default the allocator will be created as a LoadBalancer
      # we do not want it exposed outside of the cluster, so setting it
      # to Cluster IP
      serviceType: ClusterIP
      # setup the allocator to handle http traffic
      http:
        enabled: true
        port: 80
        portName: http
        targetPort: 8443
        nodePort: 0
      # disable grpc for now
      grpc:
        enabled: false
        port: 443
        portName: grpc
        targetPort: 8443
        nodePort: 0
    serviceMetrics:
      name: agones-allocator-metrics-service
      annotations: {}
      http:
        enabled: true
        port: 8080
        # called metrics to avoid name conflicts with the http port
        portName: metrics
gameservers:
  namespaces:
    - board
