apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: pre-agones
deploy:
  kubectl:
    manifests:
      - k8s/*.yml
---
apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: agones
deploy:
  helm:
    releases:
      - name: orimservers
        remoteChart: agones
        namespace: agones-sys
        createNamespace: true
        repo: https://agones.dev/chart/stable
        valuesFiles:
          - helm/values.yaml
        version: 1.36.0
requires:
  - configs:
      - "pre-agones"
