apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: server
build:
  artifacts:
  - image: orim/board-server
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/*.yml
