apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: server
build:
  artifacts:
  - image: orim/board-server
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/*.yml
profiles:
- name: agones
  patches:
  - op: replace
    path: /build/artifacts/0/docker/dockerfile
    value: Dockerfile.agones
  - op: replace
    path: /deploy/kubectl/manifests/0
    value: k8s-agones/*.yml
