apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: server
build:
  artifacts:
  - image: gcr.io/theta-computing-366519/board-server
    docker:
      dockerfile: Dockerfile.agones
  local: {}
deploy:
  kubectl:
    manifests:
    - k8s-agones/*.yml
