apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: board-server
  namespace: board
spec:
  replicas: 1
  template:
    spec:
      ports:
      - name: default
        portPolicy: Dynamic # Default is 'Dynamic'
        containerPort: 8888
        protocol: TCP
      template:
        spec:
          containers:
            - image: orim/board-server:latest
              name: board-server
              imagePullPolicy: IfNotPresent
              resources:
                requests:
                  memory: "64Mi"
                  cpu: "20m"
                limits:
                  memory: "64Mi"
                  cpu: "20m"
