apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: api
build:
  artifacts:
  - image: orim/api
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/*.yml
profiles:
- name: agones
  patches:
  - op: replace
    path: /build/artifacts/0/docker/dockerfile
    value: Dockerfile.agones
- name: kind
  patches:
  - op: replace
    path: /build/artifacts/0/image
    value: localhost:5001/api