name: Server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check Server
      working-directory: ./server
      run: cargo check --verbose
    - name: Run Server Tests
      working-directory: ./server
      run: cargo test --verbose
    - name: Check API Server
      working-directory: ./api
      run: cargo check --verbose
    - name: Run API Tests
      working-directory: ./api
      run: cargo test --verbose